Refactor temperature calculation
linkedin/Liger-Kernel pull request #444
Opened 2024-12-09 11:20 UTC by austin362667

## Summary

Addressed the part of issue raised in https://github.com/linkedin/Liger-Kernel/issues/441

Moving the scale temperature outside the `distillation_loss_fn` is fine as well. Keep the `loss_fn` simpler, and the rest can be handled in the `forward` function beforehand. Thanks to the advice by @Tcc0403 

## Testing Done

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [X] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

2024-12-10 00:28 UTC, ByronHsu approved these changes

2024-12-10 00:28 UTC, ByronHsu commented
please resolve the conflict

2024-12-10 00:28 UTC, ByronHsu requested changes
address conflict

2024-12-10 02:20 UTC, austin362667 commented
@ByronHsu Sorry for the late response. Conflict addressed. Thank you~

2024-12-11 22:14 UTC, lancerts approved these changes

2024-12-31 12:55 UTC, Tcc0403 approved these changes

2025-01-01 08:18 UTC, Tcc0403 approved these changes

2025-01-01 08:19 UTC, merged