Fix Preference Loss and Refactor for Readability
linkedin/Liger-Kernel pull request #484
Opened 2024-12-17 03:10 UTC by austin362667

## Summary

Thanks to @winglian and @shivam15s noticed and fixed this https://github.com/linkedin/Liger-Kernel/pull/481.

This PR suggest negating the preference loss terms to align with the formulas in the docstrings, while maintaining the base preference structure as `nll_loss + preference_loss`. This would make our loss computations more consistent since both terms would represent losses to be minimized.

This PR also tightened the tolerance in case of encountering a similar issue.

## Testing Done

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [X] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

2024-12-19 18:23 UTC, shivam15s requested changes

2024-12-20 02:16 UTC, austin362667 commented on test/chunked_loss/test_cpo_loss.py
>              )
Sure! Thank you for reviewing.

2024-12-20 23:15 UTC, yundai424 approved these changes

2024-12-20 23:16 UTC, shivam15s approved these changes

2024-12-20 23:17 UTC, merged